import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { validateEnv } from './utils/env'

validateEnv();
import NotificationsModal from '@/components/modals/NotificationModal';
import ToasterProvider from './providers/ToasterProvider';
import RefreshOnEditSave from '@/components/RefreshOnEditSave';
import LoginModal from '@/components/modals/LoginModal';
import getCurrentUser from './actions/getCurrentUser';
import ClientProviders from '@/components/ClientProviders';
import MessageModal from '@/components/modals/MessageModal';
import { CategoryProvider } from '@/CategoryContext';
import { FilterProvider } from '@/FilterContext';
import FilterModal from '@/components/modals/FilterModal';
import ForgotPasswordModal from '@/components/modals/ForgotPasswordModal';
import ResetPasswordModal from '@/components/modals/ResetPasswordModal';
import InboxModal from '@/components/modals/InboxModal';
import { ThemeProvider } from './context/ThemeContext';
import StripeCheckoutModal from '@/components/modals/StripeCheckoutModal';
import ReviewModal from '@/components/modals/ReviewModal';
import ComingSoonGate from '@/ComingSoonGate';
import LayoutContent from '@/LayoutContent';
import UserMenuModal from '@/components/modals/UserMenuModal';
import CreateModal from '@/components/modals/CreateModal';
import LocationModal from '@/components/modals/LocationModal';
import WelcomeModal from '@/components/modals/WelcomeModal';
import WalkthroughOverlay from '@/components/walkthrough/WalkthroughOverlay';
import UpgradeModal from '@/components/modals/UpgradeModal';
import UnreadBadgeProvider from '@/components/UnreadBadgeProvider';
import NavigationProgress from '@/components/NavigationProgress';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#0c0a09' },
  ],
}

export const metadata: Metadata = {
  title: {
    default: 'ForMe — Your Complete Business Ecosystem',
    template: '%s | ForMe',
  },
  description: 'Book services, manage your business, and grow your professional presence — all in one platform.',
  applicationName: 'ForMe',
  appleWebApp: {
    capable: true,
    title: 'ForMe',
    statusBarStyle: 'black-translucent',
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    // Default favicon is generated by app/icon.tsx (square, properly padded).
    apple: [{ url: '/logos/fm-logo.png', sizes: '180x180', type: 'image/png' }],
  },
  openGraph: {
    type: 'website',
    siteName: 'ForMe',
    title: 'ForMe — Your Complete Business Ecosystem',
    description: 'Book services, manage your business, and grow your professional presence — all in one platform.',
    images: [{ url: '/api/og?title=ForMe&description=Your+Complete+Business+Ecosystem', width: 1200, height: 630 }],
  },
  twitter: {
    card: 'summary_large_image',
    images: ['/api/og?title=ForMe&description=Your+Complete+Business+Ecosystem'],
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'https://forme.app'),
}

export const dynamic = 'force-dynamic';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default async function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  const isFirstTimeUser =
    currentUser &&
    new Date().getTime() - new Date(currentUser.createdAt).getTime() < 5 * 60 * 1000;

  return (
    <FilterProvider>
      <CategoryProvider>
        <ClientProviders>
          <ThemeProvider>
            <html lang="en">
              <body className={inter.className}>
              <ComingSoonGate>
                <a
                  href="#main-content"
                  className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[10000] focus:px-4 focus:py-2 focus:rounded-xl focus:bg-stone-900 focus:text-white dark:focus:bg-white dark:focus:text-stone-900 focus:shadow-lg focus:text-[13px] focus:font-medium"
                >
                  Skip to main content
                </a>
                <NavigationProgress />
                <main id="main-content" className="min-h-screen">
                  <LayoutContent>
                    {children}
                  </LayoutContent>
                </main>

                {/* Auto-refresh after edit flows save */}
                <RefreshOnEditSave />

                {/* Modals */}
                <ToasterProvider/>
                <ReviewModal/>
                <InboxModal/>
                <StripeCheckoutModal />
                <ForgotPasswordModal/>
                <ResetPasswordModal/>
                <MessageModal />
                <NotificationsModal />
                <FilterModal/>
                <LoginModal />
                <UserMenuModal currentUser={currentUser} />
                <CreateModal />
                <LocationModal />
                {/* <WelcomeModal currentUser={currentUser} /> */}
                <UpgradeModal />
                <WalkthroughOverlay />
                <UnreadBadgeProvider />
              </ComingSoonGate>
              </body>
            </html>
          </ThemeProvider>
        </ClientProviders>
      </CategoryProvider>
    </FilterProvider>
  )
}