import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic'
import './globals.css'
import { validateEnv } from './utils/env'

validateEnv();
import ToasterProvider from './providers/ToasterProvider';
import RefreshOnEditSave from '@/components/RefreshOnEditSave';
import getCurrentUser from './actions/getCurrentUser';
import ClientProviders from '@/components/ClientProviders';
import { CategoryProvider } from '@/CategoryContext';
import { FilterProvider } from '@/FilterContext';
import { ThemeProvider } from './context/ThemeContext';
import ComingSoonGate from '@/ComingSoonGate';
import LayoutContent from '@/LayoutContent';
import UnreadBadgeProvider from '@/components/UnreadBadgeProvider';
import NavigationProgress from '@/components/NavigationProgress';

// Modals are lazy-loaded — they're hidden by default, no need in the initial bundle.
const LoginModal = dynamic(() => import('@/components/modals/LoginModal'), { ssr: false });
const NotificationsModal = dynamic(() => import('@/components/modals/NotificationModal'), { ssr: false });
const MessageModal = dynamic(() => import('@/components/modals/MessageModal'), { ssr: false });
const FilterModal = dynamic(() => import('@/components/modals/FilterModal'), { ssr: false });
const ForgotPasswordModal = dynamic(() => import('@/components/modals/ForgotPasswordModal'), { ssr: false });
const ResetPasswordModal = dynamic(() => import('@/components/modals/ResetPasswordModal'), { ssr: false });
const InboxModal = dynamic(() => import('@/components/modals/InboxModal'), { ssr: false });
const StripeCheckoutModal = dynamic(() => import('@/components/modals/StripeCheckoutModal'), { ssr: false });
const ReviewModal = dynamic(() => import('@/components/modals/ReviewModal'), { ssr: false });
const ReservationModal = dynamic(() => import('@/components/modals/ReservationModal'), { ssr: false });
const UserMenuModal = dynamic(() => import('@/components/modals/UserMenuModal'), { ssr: false });
const CreateModal = dynamic(() => import('@/components/modals/CreateModal'), { ssr: false });
const LocationModal = dynamic(() => import('@/components/modals/LocationModal'), { ssr: false });
const UpgradeModal = dynamic(() => import('@/components/modals/UpgradeModal'), { ssr: false });
const WalkthroughOverlay = dynamic(() => import('@/components/walkthrough/WalkthroughOverlay'), { ssr: false });

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#0c0a09' },
  ],
}

export const metadata: Metadata = {
  title: {
    default: 'ForMe — Your Complete Business Ecosystem',
    template: '%s | ForMe',
  },
  description: 'Book services, manage your business, and grow your professional presence — all in one platform.',
  applicationName: 'ForMe',
  appleWebApp: {
    capable: true,
    title: 'ForMe',
    statusBarStyle: 'black-translucent',
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    // Default favicon is generated by app/icon.tsx (square, properly padded).
    apple: [{ url: '/logos/fm-logo.png', sizes: '180x180', type: 'image/png' }],
  },
  openGraph: {
    type: 'website',
    siteName: 'ForMe',
    title: 'ForMe — Your Complete Business Ecosystem',
    description: 'Book services, manage your business, and grow your professional presence — all in one platform.',
    images: [{ url: '/api/og?title=ForMe&description=Your+Complete+Business+Ecosystem', width: 1200, height: 630 }],
  },
  twitter: {
    card: 'summary_large_image',
    images: ['/api/og?title=ForMe&description=Your+Complete+Business+Ecosystem'],
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'https://forme.app'),
}


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default async function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <FilterProvider>
      <CategoryProvider>
        <ClientProviders>
          <ThemeProvider>
            <html lang="en">
              <body className={inter.className}>
              <ComingSoonGate>
                <a
                  href="#main-content"
                  className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[10000] focus:px-4 focus:py-2 focus:rounded-xl focus:bg-stone-900 focus:text-white dark:focus:bg-white dark:bg-stone-900 dark:focus:text-stone-900 dark:text-stone-100 focus:shadow-elevation-2 focus:text-[13px] focus:font-medium"
                >
                  Skip to main content
                </a>
                <NavigationProgress />
                <main id="main-content" className="min-h-screen">
                  <LayoutContent currentUser={currentUser}>
                    {children}
                  </LayoutContent>
                </main>

                {/* Auto-refresh after edit flows save */}
                <RefreshOnEditSave />

                {/* Modals */}
                <ToasterProvider/>
                <ReviewModal/>
                <ReservationModal/>
                <InboxModal/>
                <StripeCheckoutModal />
                <ForgotPasswordModal/>
                <ResetPasswordModal/>
                <MessageModal />
                <NotificationsModal />
                <FilterModal/>
                <LoginModal />
                <UserMenuModal currentUser={currentUser} />
                <CreateModal />
                <LocationModal />
                <UpgradeModal />
                <WalkthroughOverlay />
                <UnreadBadgeProvider />
              </ComingSoonGate>
              </body>
            </html>
          </ThemeProvider>
        </ClientProviders>
      </CategoryProvider>
    </FilterProvider>
  )
}